### ISSUE TITLE
Alternate of moviepy

### ISSUE THREAD

**Issue by Sannidhya127** [foggynight/grayscale#1]
hello fella! I see you are using moviepy module in the code. For some unknown reasons my pc fails running any script having moviepy in it despite installing it. Do you know any alternate of moviepy or a way to fix this issue?

**Comment by foggynight** [comment]
Hello, I'm not super familiar with `pip` so this may take a bit of experimenting, but could you try executing two commands and show me their output:

1. `pip install --user moviepy`
2. `pip show moviepy`

Also, what OS are you using, and are you sure it's an issue with `moviepy` specifically (as opposed to having an outdated version of `python` itself or of `opencv-python`)?

**Comment by Sannidhya127** [comment]
Thanks mate! Btw I use win 11 and used the pip install --user moviepy and it surprisingly worked. I don't know what was the issue but it is solved now. 👍 💯 🥇 )

**Comment by foggynight** [comment]
Great, no problem!
